### ISSUE TITLE
currency_rate_update -  SSL: CERTIFICATE_VERIFY_FAILED  - Odoo 12

### ISSUE THREAD

**Issue by movaldesarrollo** [OCA/currency#170]
Hola instalando el módulo en mi Odoo 12, he tenido este error y no se que puede ser.
Alguien sabe como puedo solucionarlo o que lo ocasiona?

2023-05-10 13:05:09,607 3408 WARNING GESMOVAL_DB odoo.addons.currency_rate_update.models.res_currency_rate_provider: Currency Rate Provider "European Central Bank" failed to obtain data since 2023-03-02 until 2023-05-10 
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\http\client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\ssl.py", line 808, in __init__
    self.do_handshake()
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\currency_rate_update\models\res_currency_rate_provider.py", line 150, in _update
    date_to
  File "C:\Program Files (x86)\Odoo 12.0\server\odoo\addons\currency_rate_update\models\res_currency_rate_provider_ECB.py", line 62, in _obtain_rates
    with urlopen(url) as response:
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Program Files (x86)\Odoo 12.0\python\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)>

**Comment by andre6622** [comment]
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>

**Comment by andre6622** [comment]
What do I need to do? When this happens in Odoo 16: 
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)>
