### ISSUE TITLE
currency_rate_update install error

### ISSUE THREAD

**Issue by misuv** [OCA/currency#18]
Hi

I tried to install currency_rate_update on Odoo 11 and I received the following error:

`Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/models.py", line 1023, in _validate_fields
    if extra_error:
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 330, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 714, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 664, in apply_view_inheritance
    source = self.apply_view_inheritance(source, view_id, model, root_id=root_id)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 663, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 641, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 503, in raise_view_error
    raise ValueError(message)
ValueError: Element '<label for="module_currency_rate_live">' cannot be located in parent view

Error context:
View `currency_rate_update.res.config.settings.form`
[view_id: 1107, xml_id: n/a, model: res.config.settings, parent_id: 504]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 398, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/odoo/odoo-server/odoo/models.py", line 3356, in create
  File "/odoo/odoo-server/odoo/fields.py", line 1070, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo/odoo-server/odoo/models.py", line 3065, in write
    else:
  File "/odoo/odoo-server/odoo/models.py", line 3231, in _write
    parent_vals[name] = vals[name]
  File "/odoo/odoo-server/odoo/models.py", line 1027, in _validate_fields
    raise ValidationError('\n'.join(errors))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nElement \'<label for="module_currency_rate_live">\' cannot be located in parent view\n\nError context:\nView `currency_rate_update.res.config.settings.form`\n[view_id: 1107, xml_id: n/a, model: res.config.settings, parent_id: 504]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-40>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/odoo/odoo-server/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_model.py", line 1469, in _update
    record = record.create(values)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 398, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/odoo/odoo-server/odoo/models.py", line 3356, in create
  File "/odoo/odoo-server/odoo/fields.py", line 1070, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 266, in _inverse_arch
    view.write(data)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 414, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo/odoo-server/odoo/models.py", line 3065, in write
    else:
  File "/odoo/odoo-server/odoo/models.py", line 3231, in _write
    parent_vals[name] = vals[name]
  File "/odoo/odoo-server/odoo/models.py", line 1027, in _validate_fields
    raise ValidationError('\n'.join(errors))
odoo.tools.convert.ParseError: "Error while validating constraint

Element '<label for="module_currency_rate_live">' cannot be located in parent view

Error context:
View `currency_rate_update.res.config.settings.form`
[view_id: 1107, xml_id: n/a, model: res.config.settings, parent_id: 504]
None" while parsing /odoo/custom/addons/currency_rate_update/views/res_config_settings.xml:8, near
<record id="view_res_config_settings" model="ir.ui.view">
        <field name="name">currency_rate_update.res.config.settings.form</field>
        <field name="model">res.config.settings</field>
        <field name="inherit_id" ref="account.res_config_settings_view_form"/>
        <field name="arch" type="xml">
            <data><field name="module_currency_rate_live" position="before">
                <field name="auto_currency_up" class="oe_inline"/>
            </field>
            <label for="module_currency_rate_live" position="before">
                <label for="auto_currency_up"/>
                <div class="text-muted">
                    Update exchange rates automatic from currency_rate_update module
                </div>
            </label>
        </data></field>
    </record>`

any help please?

**Comment by moylop260** [comment]
Duplicated with https://github.com/OCA/currency/issues/17#comment-382001615

Check the comment too please

**Comment by pedrobaeza** [comment]
Maybe Python 2 instead of 3?
