### ISSUE TITLE
currency_rate_update: invalid syntax????

### ISSUE THREAD

**Issue by bd5dml77** [OCA/currency#22]
2018-06-12 07:48:51,467 45472 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "H:\GOdoo11\runtime\python\lib\site-packages\werkzeug\serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "H:\GOdoo11\runtime\python\lib\site-packages\werkzeug\serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "H:\GOdoo11\source\odoo\service\server.py", line 250, in app
    return self.app(e, s)
  File "H:\GOdoo11\source\odoo\service\wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "H:\GOdoo11\source\odoo\service\wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "H:\GOdoo11\source\odoo\http.py", line 1315, in __call__
    self.load_addons()
  File "H:\GOdoo11\source\odoo\http.py", line 1347, in load_addons
    m = __import__('odoo.addons.' + module)
  File "H:\GOdoo11\source\odoo\modules\module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 1, in <module>

  File "H:\GOdoo11\myaddons\currency_rate_update\models\__init__.py", line 1, in <module>
    from . import currency_rate_update
  File "H:\GOdoo11\myaddons\currency_rate_update\models\currency_rate_update.py", line 11, in <module>
    from ..services.currency_getter_interface import CurrencyGetterType
  File "H:\GOdoo11\myaddons\currency_rate_update\services\__init__.py", line 3, in <module>
    from . import update_service_ECB
  File "H:\GOdoo11\myaddons\currency_rate_update\services\update_service_ECB.py", line 3, in <module>
    from .currency_getter_interface import CurrencyGetterInterface
File "H:\GOdoo11\myaddons\currency_rate_update\services\currency_getter_interface.py", line 64
    class CurrencyGetterInterface(object,metaclass=CurrencyGetterType):
                                                  ^
SyntaxError: invalid syntax

**Comment by pedrobaeza** [comment]
The problem is still on your deployment, and you don't provide any new detail. Try on Linux.
