### ISSUE TITLE
[11.0] Adding this repository crashes Odoo

### ISSUE THREAD

**Issue by gustavovalverde** [OCA/currency#44]
```python
2019-03-14 23:29:45,169 23846 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/odoo/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/odoo/venv/lib/python3.7/site-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/odoo/odoo-server/src/odoo/odoo/service/wsgi_server.py", line 164, in application
    return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
  File "/odoo/venv/lib/python3.7/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/odoo/odoo-server/src/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 1318, in __call__
    self.load_addons()
  File "/odoo/odoo-server/src/odoo/odoo/http.py", line 1350, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/odoo/odoo-server/src/odoo/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 1, in <module>

  File "/odoo/odoo-server/src/custom/oca/currency/currency_rate_update_cmc/services/__init__.py", line 1, in <module>
    from . import update_service_CMC
  File "/odoo/odoo-server/src/custom/oca/currency/currency_rate_update_cmc/services/update_service_CMC.py", line 6, in <module>
    from odoo.addons.currency_rate_update.services.currency_getter_interface \
ModuleNotFoundError: No module named 'odoo.addons.currency_rate_update.services'
```

**Comment by gustavovalverde** [comment]
cc: @jbeficent

**Comment by pedrobaeza** [comment]
The import should be protected.

**Comment by gustavovalverde** [comment]
This is still an issue. When automating install we have to:

`rm */currency/currency_rate_update_cm`
