### ISSUE TITLE
[13.0] [currency_rate_update] Can't create update service

### ISSUE THREAD

**Issue by sergiuga** [OCA/currency#76]
First I get this error: 

Error:

Traceback:
TypeError: Cannot read property 'tooltip' of undefined
    at Class.<anonymous> (https://abclima.ro/web/content/968-7cb673c/web.assets_common.js:4135:889)
    at Class.trigger (https://abclima.ro/web/content/968-7cb673c/web.assets_common.js:3942:180)
    at Class.trigger (https://abclima.ro/web/content/968-7cb673c/web.assets_common.js:3948:148)
    at Class.destroy (https://abclima.ro/web/content/968-7cb673c/web.assets_common.js:3881:269)
    at Class.prototype.<computed> [as destroy] (https://abclima.ro/web/content/968-7cb673c/web.assets_common.js:3860:488)
    at Class.trigger (https://abclima.ro/web/content/968-7cb673c/web.assets_common.js:3942:180)
    at Class.trigger (https://abclima.ro/web/content/968-7cb673c/web.assets_common.js:3948:148)
    at Class._pushController (https://abclima.ro/web/content/1155-d93f10c/web.assets_backend.js:429:634)
    at https://abclima.ro/web/content/1155-d93f10c/web.assets_backend.js:455:73

And after confirming this error, I get the next one: 

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo13/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo13/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo13/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1320, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo13/odoo/odoo/api.py", line 388, in call_kw
    model.flush()
  File "/opt/odoo13/odoo/odoo/models.py", line 5376, in flush
    self.recompute()
  File "/opt/odoo13/odoo/odoo/models.py", line 5784, in recompute
    process(next(iter(fields_to_compute)))
  File "/opt/odoo13/odoo/odoo/models.py", line 5767, in process
    recs.mapped(field.name)
  File "/opt/odoo13/odoo/odoo/models.py", line 5193, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/opt/odoo13/odoo/odoo/models.py", line 5152, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/opt/odoo13/odoo/odoo/models.py", line 5152, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/opt/odoo13/odoo/odoo/models.py", line 5597, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo13/odoo/odoo/fields.py", line 991, in __get__
    self.compute_value(recs)
  File "/opt/odoo13/odoo/odoo/fields.py", line 1105, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo13/odoo/odoo/models.py", line 3902, in _compute_field_value
    getattr(self, field.compute)()
  File "/opt/odoo13/odoo-custom-addons/currency_rate_update/models/res_currency_rate_provider.py", line 85, in _compute_name
    )[0][1]
IndexError: list index out of range

**Comment by ossimantylahti** [comment]
Confirmed on Odoo 13 CE new empty server with USD, EUR and Mexican pesos.
 Steps to reproduce:

Invoicing -> Configuration menu -> Currency update services (under Accounting).

Click "+Create", an error dialog appears and closes inmediately

Open Select Source servide and select European Central Bank.

As soon as you select that, an error appears:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/opt/odoo/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 396, in call_kw
    model.flush()
  File "/opt/odoo/odoo/odoo/models.py", line 5343, in flush
    self.recompute()
  File "/opt/odoo/odoo/odoo/models.py", line 5744, in recompute
    process(next(iter(fields_to_compute)))
  File "/opt/odoo/odoo/odoo/models.py", line 5728, in process
    recs.mapped(field.name)
  File "/opt/odoo/odoo/odoo/models.py", line 5160, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/opt/odoo/odoo/odoo/models.py", line 5119, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/opt/odoo/odoo/odoo/models.py", line 5119, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/opt/odoo/odoo/odoo/models.py", line 5564, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo/odoo/fields.py", line 950, in __get__
    self.compute_value(recs)
  File "/opt/odoo/odoo/odoo/fields.py", line 1060, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/odoo/odoo/models.py", line 3880, in _compute_field_value
    getattr(self, field.compute)()
  File "/opt/odoo/custom_addons/currency_rate_update/models/res_currency_rate_provider.py", line 85, in _compute_name
    )[0][1]
IndexError: list index out of range
```
