### ISSUE TITLE
decode() argument 'encoding' must be str, not None

### ISSUE THREAD

**Issue by ghost** [OCA/currency#99]
When testing the migration I have done for TransferWise module to Odoo 13 it errors out when trying to bulk pull the rates with the following error;

`
2021-03-22 19:31:34,970 626 WARNING dummydb odoo.addons.currency_rate_update.models.res_currency_rate_provider: Currency Rate Provider "TransferWise.com" failed to obtain data since 2021-01-01 until 2021-03-22 
Traceback (most recent call last):
  File "/etc/odoo/currency/currency_rate_update/models/res_currency_rate_provider.py", line 120, in _update
    data = provider._obtain_rates(
  File "/etc/odoo/currency/currency_rate_update_transferwise/models/res_currency_rate_provider_TransferWise.py", line 72, in _obtain_rates
    data = json.loads(self._transferwise_provider_retrieve(url))
  File "/etc/odoo/currency/currency_rate_update_transferwise/models/res_currency_rate_provider_TransferWise.py", line 92, in _transferwise_provider_retrieve
    content = response.read().decode(response.headers.get_content_charset())
TypeError: decode() argument 'encoding' must be str, not None
`

**Comment by pedrobaeza** [comment]
Sorry, but this is out of scope of this issue tracker. Only official code is supported.
